name: Validations

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install Ceedling
        run: gem install ceedling
      - name: Install GCov Reporter
        run: pip install gcovr
      - name: Run Format Validations
        uses: pre-commit/action@v3.0.0
      - name: Run Unit Tests
        run: cd TP4 && ceedling clobber gcov:all utils:gcov
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: TP4/build/artifacts/gcov/report.xml
          reporter: jest-junit
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TP4/build/artifacts/gcov/GcovCoverageCobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "60 80"
      - name: Output to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
  Tp3:
    runs-on: ubuntu-latest
    steps:
      # Workaround for https://github.com/actions/runner-images/issues/8659
      - uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
      - name: Install libelf development package
        run: sudo apt-get install -y libelf-dev
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install GCov Reporter
        run: pip install gcovr
      - name: Run Format Validations
        uses: pre-commit/action@v3.0.0
      - name: Install just
        run: sudo snap install --edge --classic just
      - name: Run coverage
        run: cd TP3 && just coverage
      - name: Create HTML artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-css-artifacts
          path: TP3/coverage/
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: test
          message: |
            ```
            ${{ env.test_result }}
            Coverage report for TP3 was uploaded as artifact.
            ```
